active = "dev"

[profiles.dev]
PREFECT_API_URL = "http://127.0.0.1:4200/api"
PREFECT_API_DATABASE_CONNECTION_URL = "postgresql+asyncpg://prefect:prefect@localhost:5436/prefect_dev"

[profiles.prod]
PREFECT_API_URL = "http://127.0.0.1:4201/api"
PREFECT_API_DATABASE_CONNECTION_URL = "postgresql+asyncpg://prefect:prefect@localhost:5437/prefect_prod"
